language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  on:
    all_branches: true
  edge: true
  provider: cloudfoundry
  username: Ritika.Patil@sas.com
  api: https://api.run.pivotal.io
  organization: Ritika.Patil
  space: staging
  password:
    secure: N8Cnyjoelz4YoO+XblVbyzsf01+o0rFvlLbBvsnv9llTePDqrByTJ+zVHngOCAfQ8W7m2wC9GUokCpi3jZUSRYDGv5EWTnaGa4GTS8eI5XWSRH35XKajdMOn64sMJX6zEPp17iptOEYHqOElxEuQ87uwtYT1kd2w7X79u3EhWbt5+sUBpXOK0dQE8qo+XMxrGR+wm8i76LDWYI6hgq3MNFPp8qIjcdx8ToYSzl2WbkXl0gOtiT5IJbjPaYWlLL7jfPQwaQE5TteG4bXwBNNLwkBo4+LH75hCOym70jQh8LtY9EOWurhmYJct7WJMCtlPbpDCiDY7bmzun+CxbD7r45MGHi9vAaGcJ0+DNfnbiJYlI+pR8k4YgVcwQWrt9TWQ0d+O1j4TOA8K3EMhxY3ROyWS0SoUHfit957SvdFjLJgwtmtnfYk7QEvoFXYUgUPeOxjsZwZRdK3hzZ4V4Kmg6AZHMef25h2nJRavoG5c4aIx1YyJczru7qXLLRM6fkhKrk7xRcZaElfF1l9r7GXQWCXiouIrBiqhM3l6wo5BsrTC1v9jcUPIsaiB9kTlyfGdxyFjma9On8dZXW4IvggTPt2TFypF4/MqqZwiUbXwHzhonIQDiv2aR9HheB/XrISZIC66l+zMDNCokstWrsaCtVfRie0BVUvMrnWv16LMKVg=
